version: '3.8'

name: "castor-stdlib"

services:

  main:
    image: castor/stdlib:dev
    build:
      context: ./.castor/docker
      dockerfile: ./lib/Dockerfile
      target: dev
    volumes:
      - ./:/castor/lib
    user: ${UID:-1000}
