version: '3.8'

name: "castor-stdlib"

services:

  lib:
    image: castor/stdlib:dev
    build:
      context: ./.castor/docker
      dockerfile: ./lib/Dockerfile
      target: dev
    container_name: lib.castor-stdlib.dev
    volumes:
      - ./:/castor/lib
    user: ${UID:-1000}
