#!/usr/bin/env bash
set -e

COMPOSE=${COMPOSE_CMD:-docker compose}
CMD=$1
SDK=$0

function compose() {
    $COMPOSE "$@"
}

function sdk() {
    $SDK "$@"
}

function stack_build() {
    compose build --pull
}

function stack_exec() {
    compose exec "$@"
}

function stack_run() {
    compose run --rm "$@"
}

function stack_boot() {
    compose up --remove-orphans --wait
}

function stack_destroy() {
    compose down
}

function stack_stop() {
    compose stop
}

function stack_start() {
    compose start
}

function install_dependencies() {
    stack_run main composer install
}

function sync() {
    stack_exec main composer sync
}

function test() {
    stack_run main vendor/bin/phpunit "$@"
}

function static_analysis() {
    stack_run main vendor/bin/psalm --stats --no-cache
}

function code_style_check() {
    stack_run main vendor/bin/php-cs-fixer fix --dry-run -v
}

function code_style_fix() {
    stack_run main vendor/bin/php-cs-fixer fix
}

shift

case $CMD in
  'init')
    stack_build
    install_dependencies
    stack_boot
    echo ""
    echo "Ready for development!"
  ;;
  'compose')
    compose "$@"
  ;;
  'reset')
    stack_destroy
    install_dependencies
    stack_boot
  ;;
  'php')
    stack_exec main php "$@"
  ;;
  'composer')
    stack_exec main composer "$@"
  ;;
  'fmt')
    code_style_fix
  ;;
  'types')
    static_analysis
  ;;
  'bench')
    stack_exec main ./vendor/bin/phpbench run
  ;;
  'test')
    test "$@"
  ;;
  'shell')
    stack_exec main ash
  ;;
  'sync')
    sync
    sdk composer dump-autoload
  ;;
  'pr')
    sync
    code_style_fix
    static_analysis
    test
  ;;
  '')
    echo "You must specify a command"
  ;;
  *)
    echo "Command $CMD is not valid"
  ;;
esac